:toc:
:toc-placement!:
:toclevels: 4
:imagesdir: https://raw.githubusercontent.com/lyrasis/dts-data-migration-docs/main/images

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Legacy objectexit procedure data and relationships export

[WARNING]
====
The query returning the objectexit procedure data was developed for a custom UI profile closely based on the community supported anthro domain profile.

It may need to be updated for other profiles, if there are differences in the objectexit procedure.
====

NOTE: The query returning relationship info between objectexit procedures and other records should work for all profiles.

toc::[]

== objectexit procedure data

IMPORTANT: You must set the site timezone before running this query.
See xref:../common_patterns.adoc#timezone[Converting date values to site timezone].

[WARNING]
====
*Only the `dateDisplayDate` field is exported from the `exitDateGroup` structured date.*

Run the xref:../reports/structured_date_field_data.adoc#noncomputablecheck[non-computable structure date value check query] to determine if any additional structured date detail fields need to be selected in order to prevent data loss.
====

[source,sql]
----
WITH
    base AS (
        SELECT
            oec.*,
            hier.name AS objectexit_csid,
            sdg.datedisplaydate AS exitdate,
            TO_CHAR(
                core.updatedat at TIME ZONE CURRENT_SETTING('datamig.client_timezone'),
                'YYYY-MM-DD'
            ) AS updated_date,
            core.updatedby,
            core.updatedat
        FROM
            objectexit_common oec
            INNER JOIN misc ON misc.id = oec.id
            AND misc.lifecyclestate != 'deleted'
            INNER JOIN collectionspace_core core ON core.id = oec.id
            INNER JOIN hierarchy hier ON oec.id = hier.id
            LEFT JOIN hierarchy dh ON dh.parentid = oec.id
            AND dh.primarytype = 'structuredDateGroup'
            AND dh.name = 'objectexit_common:exitDateGroup'
            LEFT JOIN structureddategroup sdg ON sdg.id = dh.id
    ),
    methods AS (
        SELECT
            meth.id,
            STRING_AGG(
                meth.item,
                '|'
                ORDER BY
                    meth.pos
            ) AS methods
        FROM
            objectexit_common_exitmethods meth
        GROUP BY
            meth.id
    ),
    apps AS (
        SELECT
            COALESCE(deurn (dag.deaccessionapprovalstatus), '%NULLVALUE%') AS deaccessionapprovalstatus,
            COALESCE(deurn (dag.deaccessionapprovalgroup), '%NULLVALUE%') AS deaccessionapprovalgroup,
            COALESCE(
                TO_CHAR(
                    dag.deaccessionapprovaldate at TIME ZONE CURRENT_SETTING('datamig.client_timezone'),
                    'YYYY-MM-DD'
                ),
                '%NULLVALUE%'
            ) AS deaccessionapprovaldate,
            COALESCE(dag.deaccessionapprovalnote, '%NULLVALUE%') AS deaccessionapprovalnote,
            COALESCE(deurn (dag.deaccessionapprovalindividual), '%NULLVALUE%') AS deaccessionapprovalindividual,
            h.parentid,
            h.pos
        FROM
            deacapprovalgroup dag
            INNER JOIN hierarchy h ON dag.id = h.id
    ),
    dastatus AS (
        SELECT
            apps.parentid AS id,
            STRING_AGG(
                apps.deaccessionapprovalstatus,
                '|'
                ORDER BY
                    apps.pos
            ) AS deaccessionapprovalstatus
        FROM
            apps
        GROUP BY
            apps.parentid
    ),
    dagroup AS (
        SELECT
            apps.parentid AS id,
            STRING_AGG(
                apps.deaccessionapprovalgroup,
                '|'
                ORDER BY
                    apps.pos
            ) AS deaccessionapprovalgroup
        FROM
            apps
        GROUP BY
            apps.parentid
    ),
    daindividual AS (
        SELECT
            apps.parentid AS id,
            STRING_AGG(
                apps.deaccessionapprovalindividual,
                '|'
                ORDER BY
                    apps.pos
            ) AS deaccessionapprovalindividual
        FROM
            apps
        GROUP BY
            apps.parentid
    ),
    dadate AS (
        SELECT
            apps.parentid AS id,
            STRING_AGG(
                apps.deaccessionapprovaldate,
                '|'
                ORDER BY
                    apps.pos
            ) AS deaccessionapprovaldate
        FROM
            apps
        GROUP BY
            apps.parentid
    ),
    danote AS (
        SELECT
            apps.parentid AS id,
            STRING_AGG(
                apps.deaccessionapprovalnote,
                '|'
                ORDER BY
                    apps.pos
            ) AS deaccessionapprovalnote
        FROM
            apps
        GROUP BY
            apps.parentid
    )
SELECT
    base.objectexit_csid,
    base.exitnumber,
    base.exitdate AS exitdategroup,
    base.exitreason,
    base.exitquantity,
    methods.methods AS exitmethod,
    dagroup.deaccessionapprovalgroup,
    daindividual.deaccessionapprovalindividual,
    dastatus.deaccessionapprovalstatus,
    dadate.deaccessionapprovaldate,
    danote.deaccessionapprovalnote,
    base.exitnote,
    base.packingnote,
    base.deaccessiondate,
    TO_CHAR(
        base.disposaldate at TIME ZONE CURRENT_SETTING('datamig.client_timezone'),
        'YYYY-MM-DD'
    ) AS disposaldate,
    deurn (base.disposalmethod) AS disposalmethod,
    base.displosalreason,
    deurn (base.disposalproposedrecipient) AS disposalproposedrecipient,
    deurn (base.disposalrecipient) AS disposalrecipient,
    deurn (base.disposalcurrency) AS disposalcurrency,
    base.displosalvalue,
    deurn (base.groupdisposalcurrency) AS groupdisposalcurrency,
    base.groupdisplosalvalue,
    base.displosalprovisos,
    base.displosalnote,
    base.updated_date,
    base.updatedby
FROM
    base
    LEFT JOIN methods ON base.id = methods.id
    LEFT JOIN dastatus ON base.id = dastatus.id
    LEFT JOIN dagroup ON base.id = dagroup.id
    LEFT JOIN daindividual ON base.id = daindividual.id
    LEFT JOIN dadate ON base.id = dadate.id
    LEFT JOIN danote ON base.id = danote.id
ORDER BY
    base.updatedat DESC
----

== objectexits are related to what other record types?

Run this to determine if more work is needed to get full info out of <<rels>>

[source,sql]
----
SELECT DISTINCT
    objectdocumenttype
FROM
    relations_common rel
WHERE
    rel.subjectdocumenttype = 'ObjectExit'
----

[#rels]
== objectexit relationship details

[IMPORTANT]
====
Run the following before you run the query.
If you switch to running queries for a different client in the same session, you will be switching to a different database, and you'll need to reset this.
====

[source,sql]
----
set datamig.client_url_base = 'https://sitecode.collectionspace.org/cspace/sitecode';
----


[source,sql]
----
SELECT
    rel.objectdocumenttype,
    COALESCE(
        collobj.objectnumber,
        acq.acquisitionreferencenumber,
        cc.conditioncheckrefnumber,
        grp.title,
        intake.entrynumber,
        media.identificationnumber,
        lmi.movementreferencenumber,
        exit.exitnumber,
        vc.valuationcontrolrefnumber,
        ''
    ) AS object_readable_id,
    CONCAT(CURRENT_SETTING('datamig.client_url_base'), '/record/all/', rel.objectcsid) AS object_app_url,
    rel.objecturi AS object_api_uri,
    oe.exitnumber AS subject_readable_id,
    CONCAT(CURRENT_SETTING('datamig.client_url_base'), '/record/all/', rel.subjectcsid) AS subject_app_url,
    rel.subjecturi AS subject_api_uri,
    TO_CHAR(
        core.updatedat at TIME ZONE CURRENT_SETTING('datamig.client_timezone'),
        'YYYY-MM-DD'
    ) AS updated_date,
    core.updatedby
FROM
    relations_common rel
    INNER JOIN hierarchy subhier ON subhier.name = rel.subjectcsid
    INNER JOIN objectexit_common oe ON subhier.id = oe.id
    INNER JOIN hierarchy objhier ON objhier.name = rel.objectcsid
    INNER JOIN misc ON misc.id = objhier.id
    AND misc.lifecyclestate != 'deleted'
    INNER JOIN collectionspace_core core ON core.id = objhier.id
    LEFT JOIN collectionobjects_common collobj ON objhier.id = collobj.id
    LEFT JOIN acquisitions_common acq ON objhier.id = acq.id
    LEFT JOIN conditionchecks_common cc ON objhier.id = cc.id
    LEFT JOIN groups_common grp ON objhier.id = grp.id
    LEFT JOIN intakes_common intake ON objhier.id = intake.id
    LEFT JOIN media_common media ON objhier.id = media.id
    LEFT JOIN movements_common lmi ON objhier.id = lmi.id
    LEFT JOIN objectexit_common exit ON objhier.id = exit.id
    LEFT JOIN valuationcontrols_common vc ON objhier.id = vc.id
WHERE
    rel.subjectdocumenttype = 'ObjectExit'
ORDER BY
    core.updatedat DESC
----
