:toc:
:toc-placement!:
:toclevels: 4

= Common patterns/snippets


toc::[]

== All records of a type

=== Person authorities

[source,sql]
----
SELECT COUNT(persons.id)
FROM persons_common persons
----

=== Objects

[source,sql]
----
SELECT COUNT(objs.id)
FROM collectionobjects_common objs
----

== Remove deleted records from query

Deleted records persist in the database with a `lifecyclestate` set to `deleted` in the informatively named `misc` table.

=== Active (non-deleted) person authorities

[source,sql]
----
SELECT COUNT(persons.id)
FROM persons_common persons
INNER JOIN misc ON misc.id = persons.id AND misc.lifecyclestate != 'deleted'
----

=== Active (non-deleted) objects

[source,sql]
----
SELECT COUNT(objs.id)
FROM collectionobjects_common objs
INNER JOIN misc ON misc.id = objs.id AND misc.lifecyclestate != 'deleted'
----

== Data for a known record from application UI

The data for a given record is usually scattered across multiple tables in the database.

Also it's a bit unclear at first how you can find a record in the database using the CSID from the end of a record's URI in the application.

There are at least two methods. Entering via `hierarchy` table is probably the most practical, because you will have to use that table to combine record field data from different tables.

=== Via `hierarchy` table

Assuming URI for the record in the application UI is:

`https://core.collectionspace.org/cspace/core/record/collectionobject/6aaf2595-2257-40f6-83b2`

=== Using `id_from_csid` function

You will need to run https://github.com/lyrasis/collectionspace-sql/blob/main/functions.adoc#id_from_csid[the `id_from_csid` function creation query] before using the following.

[source,sql]
----
WITH dbid AS (
	select id_from_csid('6aaf2595-2257-40f6-83b2') as id
), thisrec AS (
	select * from hierarchy h
	inner join dbid d on h.id = d.id
), children AS (
	select * from hierarchy h
	inner join dbid d on h.parentid = d.id
), allrows AS (
	(select * from thisrec)
     union all
    (select * from children)
)

select * from allrows
----

=== Without the function

Essentially you just rewrite the function in the `WITH dbid AS` portion.

[source,sql]
----
WITH dbid AS (
       select hierarchy.id
       from hierarchy
       where hierarchy.name = '6aaf2595-2257-40f6-83b2'
), thisrec AS (
	select * from hierarchy h
	inner join dbid d on h.id = d.id
), children AS (
	select * from hierarchy h
	inner join dbid d on h.parentid = d.id
), allrows AS (
	(select * from thisrec)
     union all
    (select * from children)
)

select * from allrows
----
