:toc:
:toc-placement!:
:toclevels: 2

= Data projects

toc::[]

== Export objectNumber, objectProductionDate, objectName, and namedCollection for all collectionobjects

* if there are multiple values in the objectProductionDate, objectName, or namedCollection fields, take only the value that appears first in the CS record
* return the dateDisplayDate element for the date field
* return the first termDisplayName element from the Work authority linked to in namedCollection

[WARNING]
====
Somewhat dangerous because it assumes unique objectNumber values across objects. This is not enforced by CS, though I knew it was the case in my data set.

It also does not remove any items marked as deleted. 
====

[source,sql]
----
WITH objects AS (
  SELECT
  hier.id AS objid,
  common.objectnumber AS objnum
from collectionobjects_common common
inner join hierarchy hier on hier.id = common.id
inner join misc on misc.id = hier.id AND misc.lifecyclestate != 'deleted'
inner join collectionspace_core core on core.id = misc.id
), prod_date_objs AS (
	SELECT DISTINCT ON (objects.objnum) objects.objnum, sdg.datedisplaydate AS date
	FROM hierarchy hier
	INNER JOIN structureddategroup sdg ON hier.id = sdg.id
	INNER JOIN objects ON hier.parentid = objects.objid
	WHERE hier.name = 'collectionobjects_common:objectProductionDateGroupList'
	ORDER BY objects.objnum ASC, hier.pos ASC
), named_coll AS (
	SELECT objects.objnum, wt.termdisplayname AS coll
	FROM objects
	INNER JOIN collectionobjects_common_namedcollections nc ON nc.id = objects.objid
	INNER JOIN works_common wc ON nc.item = wc.refname AND nc.pos = 0
	INNER JOIN hierarchy hier ON hier.parentid = wc.id AND hier.pos = 0 
	INNER JOIN worktermgroup wt ON hier.id = wt.id
), obj_names AS (
	SELECT DISTINCT ON (objects.objnum) objects.objnum, ong.objectname AS objname
	FROM hierarchy hier
	INNER JOIN objectnamegroup ong ON hier.id = ong.id
	INNER JOIN objects ON hier.parentid = objects.objid
	WHERE hier.name = 'collectionobjects_common:objectNameList'
	ORDER BY objects.objnum ASC, hier.pos ASC

)

SELECT objects.objnum, pdo.date, nc.coll, ong.objname
FROM objects
LEFT OUTER JOIN prod_date_objs pdo ON pdo.objnum = objects.objnum
LEFT OUTER JOIN named_coll nc ON nc.objnum = objects.objnum
LEFT OUTER JOIN obj_names ong ON ong.objnum = objects.objnum
----

== Publish all media handling procedure records to "All"

* This only handles adding a publishTo value to fields that have nothing in that field.

=== Count of non-deleted MH records published to All

[source,sql]
----
SELECT COUNT(mh.id)
FROM media_common mh
LEFT JOIN media_common_publishtolist pt ON mh.id = pt.id
INNER JOIN misc ON misc.id = mh.id AND misc.lifecyclestate != 'deleted'
WHERE pt.item = E'urn:cspace:{INSTANCEDOMAIN}:vocabularies:name(publishto):item:name(all)\'All\''
AND mh.identificationnumber IS NOT NULL
----

=== Count of non-deleted MH records with no publishTo value

[source,sql]
----
SELECT COUNT(mh.id)
FROM media_common mh
LEFT JOIN media_common_publishtolist pt ON mh.id = pt.id
INNER JOIN misc ON misc.id = mh.id AND misc.lifecyclestate != 'deleted'
WHERE pt.id IS NULL
AND mh.identificationnumber IS NOT NULL
----

=== Update the publishTo field of unpublished records, setting them to "All"

[source,sql]
----
WITH not_published AS (
SELECT mh.id
FROM media_common mh
LEFT JOIN media_common_publishtolist pt ON mh.id = pt.id
INNER JOIN misc ON misc.id = mh.id AND misc.lifecyclestate != 'deleted'
WHERE pt.id IS NULL
AND mh.identificationnumber IS NOT NULL
), to_insert AS (
	SELECT not_published.id,
	CAST(0 AS integer) AS pos,
	CAST(E'urn:cspace:{INSTANCEDOMAIN}:vocabularies:name(publishto):item:name(all)\'All\'' AS text) AS item
FROM not_published
)
INSERT INTO media_common_publishtolist
select * from to_insert
----

== Is an authority term used in a field in deleted object records?

Client could not delete an Archeological Culture Concept authority record. They were getting an error about the term being used in records, but the "Used In" listing in the term record and searching the CS application showed that no records were using the term.

We wanted to verify that there were hidden "deleted" object records lurking in the system, preventing term deletion.

This was made easier by the fact that only one field in the object record would have used terms from this particular authority.

[source,sql]
----
select oppg.id, h.parentid, m.lifecyclepolicy, m.lifecyclestate from objectproductionpeoplegroup oppg
inner join hierarchy h
on h.id = oppg.id
inner join misc m
on h.parentid = m.id
where oppg.objectproductionpeople = 'urn:cspace:{INSTANCEDOMAIN}:conceptauthorities:name(archculture):item:name(Prehistoric1558556422893)''Pre-Contact **DELETE - DO NOT USE **'''
----

== Copy value from old, single-valued client-custom field to new, multi-valued community profile field

* implemented a single value namedCollection field, populated by Work authority, for a client
* later added a multi-value namedCollections field, also populated by Work authority, to community profiles
* to get the client closer to community profile and fix confusion about apparent duplicate fields in search/import/export forms, we needed to migrate their data from the old field to the new field

=== count instances of client-specific field

[source,sql]
----
SELECT COUNT(coo.id) FROM public.collectionobjects_ohc coo
WHERE coo.namedcollection IS NOT NULL
----

=== count instances of community profile field

[source,sql]
----
SELECT COUNT(coc.id) FROM public.collectionobjects_common_namedcollections coc
WHERE coc.item IS NOT NULL
----

=== count objects where client-specific field is populated, but community profile field is not

[source,sql]
----
SELECT COUNT(coo.id) FROM public.collectionobjects_ohc coo
LEFT JOIN
public.collectionobjects_common_namedcollections con
ON con.id = coo.id
WHERE 
con.id IS NULL
AND coo.namedcollection IS NOT NULL
----

=== copy values in client-specific field to community profile field

[source,sql]
----
INSERT INTO public.collectionobjects_common_namedcollections (id, pos, item)
SELECT coo.id, 0, coo.namedcollection FROM public.collectionobjects_ohc coo
LEFT JOIN
public.collectionobjects_common_namedcollections con
ON con.id = coo.id
WHERE 
con.id IS NULL
AND coo.namedcollection IS NOT NULL
----

=== delete values in client-specific field

[source,sql]
----
UPDATE public.collectionobjects_ohc
SET namedcollection = null
WHERE namedcollection IS NOT NULL
----

== Set object publishTo value to public browser for conditionally selected set of objects

Only update objects where:

* object does not have a 'deleted' workflow state
* objectNumber starts with A, H, or N, and
* inventoryStatus is NOT deaccessioned, transferred, missing, or stolen, and
* publishTo value (is set, but is not NAGPRA or Do not publish) OR (publishTo value is not set)

TIP: "publishTo value is set" means there is at least one row in `collectionobjects_common_publishtolist` with `id` matching to `collectionobjects_common` `id`. There can be rows for objects in `collectionobjects_common_publishtolist` with null `item` field. These should be updated with the new value.

This project needed two separate actions: update existing publishTo values meeting criteria, and inserting new publishTo values into records meeting other criteria but having no publishTo values


.Update existing publishTo values meeting criteria
[source,sql]
----
UPDATE collectionobjects_common_publishtolist
SET item = 'urn:cspace:core.collectionspace.org:vocabularies:name(publishto):item:name(cspacepub)''CollectionSpace Public Browser'''
WHERE id IN (
  SELECT coc_pub.id
  FROM collectionobjects_common AS coc
  LEFT JOIN collectionobjects_common_inventorystatuslist AS coc_inv ON (coc.id = coc_inv.id)
  LEFT JOIN collectionobjects_common_publishtolist AS coc_pub ON (coc.id = coc_pub.id)
  INNER JOIN misc ON misc.id = coc.id AND misc.lifecyclestate != 'deleted'
  WHERE 
    (coc.objectnumber LIKE 'A%' OR coc.objectnumber LIKE 'H%' OR coc.objectnumber LIKE 'N%')
  AND
    (
      (coc_inv.item NOT LIKE '%deaccessioned%' OR coc_inv.item NOT LIKE '%transferred%'OR coc_inv.item NOT LIKE '%missing%' OR coc_inv.item NOT LIKE '%stolen%')
      OR
      coc_inv.item IS NULL) 
  AND
    coc_pub.id IS NOT NULL
  AND 
    (
  	  coc_pub.item IS NULL
  	  OR
  	  (coc_pub.item NOT LIKE '%NAGPRA%' AND coc_pub.item NOT LIKE '%Do not publish%')
    )
);
----

.Insert new publishTo values into records meeting other criteria, but having no existing publishTo values
[source,sql]
----
WITH not_published AS (
SELECT DISTINCT coc.id FROM collectionobjects_common AS coc
    LEFT JOIN collectionobjects_common_inventorystatuslist AS coc_inv ON (coc.id = coc_inv.id)
    LEFT JOIN collectionobjects_common_publishtolist AS coc_pub ON (coc.id = coc_pub.id)
    INNER JOIN misc ON misc.id = coc.id AND misc.lifecyclestate != 'deleted'
WHERE (coc.objectnumber LIKE 'A%' OR coc.objectnumber LIKE 'H%' OR coc.objectnumber LIKE 'N%')
  AND
  (
    (coc_inv.item NOT LIKE '%deaccessioned%' OR coc_inv.item NOT LIKE '%transferred%'OR coc_inv.item NOT LIKE '%missing%' OR coc_inv.item NOT LIKE '%stolen%')
    OR coc_inv.item IS NULL) 
  AND coc_pub.id IS NULL
), to_insert AS (
  SELECT not_published.id,
  CAST(0 AS integer) AS pos,
  CAST('urn:cspace:core.collectionspace.org:vocabularies:name(publishto):item:name(cspacepub)''CollectionSpace Public Browser''' AS text) AS item
  FROM not_published
)
INSERT INTO collectionobjects_common_publishtolist
SELECT * from to_insert
----

.Final count of objects published to public browser
[source,sql]
----
SELECT COUNT(coc.id) FROM collectionobjects_common AS coc
LEFT JOIN collectionobjects_common_publishtolist AS coc_pub ON (coc.id = coc_pub.id)
INNER JOIN misc ON misc.id = coc.id AND misc.lifecyclestate != 'deleted'
WHERE coc_pub.item LIKE '%Public Browser%'
----

== Indexing errors related to `annotationdate` field

Upon re-indexing, logs showed errors like:

[source]
----
org.nuxeo.ecm.core.api.NuxeoException: Could not select: SELECT "id", "annotationauthor", "annotationdate", "annotationtype", "annotationnote" FROM "annotationgroup" WHERE "id" IN (?)
Caused by: org.postgresql.util.PSQLException: Bad value for type timestamp/date/time: {1}
Caused by: java.lang.NumberFormatException: Expected time to be colon-separated, got '/'
----

.Find rows in `annotationgroup` where `annotationdate` value contains `/`
[source,sql]
----
select * from annotationgroup
where annotationdate LIKE '%/%'
----

.Get CSIDs of records containing `annotationgroup` entries with `annotationdate` values containing `/`
[source,sql]
----
SELECT HH.NAME AS CSID,
	AG.ID AS GROUPID
FROM ANNOTATIONGROUP AG
LEFT JOIN HIERARCHY H ON AG.ID = H.ID
LEFT JOIN HIERARCHY HH ON H.PARENTID = HH.ID
WHERE ANNOTATIONDATE LIKE '%/%';
----
