:toc:
:toc-placement!:
:toclevels: 4

= Authority data reports

[IMPORTANT]
====
Run the following before you start producing these reports. If you switch to running queries for a different client in the same session, you will be switching to a different database, and you'll need to set these again.

[source,sql]
----
set datamig.client_url_base = 'https://tenant.collectionspace.org/cspace/tenant';
----

====

toc::[]

== Simple thesaurus from authority vocabulary

The example below is for the person/local authority vocabulary.

nameform:: All `termDisplayName` values from term records in the vocabulary
nametype:: "preferred" if the `nameform` value is the first-occurring `termDisplayName` value in the term record
use:: The preferred name form for each form occurring in `nameform`. When `nametype` = "preferred", `nameform` and `use` are the same
rec_url:: URL to access authority term record in the user-facing application

.Sample output
[format=csv]
|===
"nameform","nametype","use","rec_url"
"Scott, Sarah","preferred","Scott, Sarah","https://tenant.collectionspace.org/cspace/tenant/record/all/00a1ea62-10aa-4fe8-8b0b"
"Gustin, Patricia A. (Wadsworth)","preferred","Gustin, Patricia A. (Wadsworth)","https://tenant.collectionspace.org/cspace/tenant/record/all/00a33eb9-5d4e-4b50-a2e4"
"Wadsworth, Patricia","variant","Gustin, Patricia A. (Wadsworth)","https://tenant.collectionspace.org/cspace/tenant/record/all/00a33eb9-5d4e-4b50-a2e4"
"Cheek, Edwin","preferred","Cheek, Edwin","https://tenant.collectionspace.org/cspace/tenant/record/all/00a4a9ee-58f4-484b-ada5"
"Fuller, Emma","preferred","Fuller, Emma","https://tenant.collectionspace.org/cspace/tenant/record/all/00a530e1-49f2-4af0-b745"
|===

[source,sql]
----
with authcsid as (
select h.name as csid
from personauthorities_common pac
inner join hierarchy h on pac.id = h.id
where pac.displayname = 'Local Persons'
),
personrecs as (
select per.id,
	h.name as termcsid
from persons_common per
inner join authcsid auth on per.inauthority = auth.csid
inner join misc on misc.id = per.id and misc.lifecyclestate != 'deleted'
inner join hierarchy h on per.id = h.id
),
prefnames as (
select
	pt.termdisplayname as nameform,
	'preferred' as nametype,
	pt.termdisplayname as use,
	concat(
    current_setting('datamig.client_url_base'), '/record/all/',
    pr.termcsid
  ) as rec_url
from persontermgroup pt
inner join hierarchy h on h.id = pt.id and h.pos = 0
inner join personrecs pr on h.parentid = pr.id
),
varnames as (
select
	pt.termdisplayname as nameform,
	'variant' as nametype,
	upt.termdisplayname as use,
	concat(
    current_setting('datamig.client_url_base'), '/record/all/',
    pr.termcsid
  ) as rec_url
from persontermgroup pt
inner join hierarchy h on h.id = pt.id and h.pos != 0
inner join personrecs pr on h.parentid = pr.id
inner join hierarchy uh on uh.parentid = pr.id and uh.pos = 0
inner join persontermgroup upt on uh.id = upt.id
)
select * from prefnames
union
select * from varnames
order by rec_url, nametype
----
