:toc:
:toc-placement!:
:toclevels: 4

= Authority data reports

[IMPORTANT]
====
Run the following before you start producing these reports. If you switch to running queries for a different client in the same session, you will be switching to a different database, and you'll need to set these again.

[source,sql]
----
set datamig.client_url_base = 'https://tenant.collectionspace.org/cspace/tenant';
----

====

toc::[]

== Simple thesaurus from authority vocabulary

The example below is for the person/local authority vocabulary.

nameform:: All `termDisplayName` values from term records in the vocabulary
nametype:: "preferred" if the `nameform` value is the first-occurring `termDisplayName` value in the term record
use:: The preferred name form for each form occurring in `nameform`. When `nametype` = "preferred", `nameform` and `use` are the same
rec_url:: URL to access authority term record in the user-facing application

.Sample output
[format=csv]
|===
"nameform","nametype","use","rec_url"
"Scott, Sarah","preferred","Scott, Sarah","https://tenant.collectionspace.org/cspace/tenant/record/all/00a1ea62-10aa-4fe8-8b0b"
"Gustin, Patricia A. (Wadsworth)","preferred","Gustin, Patricia A. (Wadsworth)","https://tenant.collectionspace.org/cspace/tenant/record/all/00a33eb9-5d4e-4b50-a2e4"
"Wadsworth, Patricia","variant","Gustin, Patricia A. (Wadsworth)","https://tenant.collectionspace.org/cspace/tenant/record/all/00a33eb9-5d4e-4b50-a2e4"
"Cheek, Edwin","preferred","Cheek, Edwin","https://tenant.collectionspace.org/cspace/tenant/record/all/00a4a9ee-58f4-484b-ada5"
"Fuller, Emma","preferred","Fuller, Emma","https://tenant.collectionspace.org/cspace/tenant/record/all/00a530e1-49f2-4af0-b745"
|===

[source,sql]
----
with authcsid as (
select h.name as csid
from personauthorities_common pac
inner join hierarchy h on pac.id = h.id
where pac.displayname = 'Local Persons'
),
personrecs as (
select per.id,
	h.name as termcsid
from persons_common per
inner join authcsid auth on per.inauthority = auth.csid
inner join misc on misc.id = per.id and misc.lifecyclestate != 'deleted'
inner join hierarchy h on per.id = h.id
),
prefnames as (
select
	pt.termdisplayname as nameform,
	'preferred' as nametype,
	pt.termdisplayname as use,
	concat(
    current_setting('datamig.client_url_base'), '/record/all/',
    pr.termcsid
  ) as rec_url
from persontermgroup pt
inner join hierarchy h on h.id = pt.id and h.pos = 0
inner join personrecs pr on h.parentid = pr.id
),
varnames as (
select
	pt.termdisplayname as nameform,
	'variant' as nametype,
	upt.termdisplayname as use,
	concat(
    current_setting('datamig.client_url_base'), '/record/all/',
    pr.termcsid
  ) as rec_url
from persontermgroup pt
inner join hierarchy h on h.id = pt.id and h.pos != 0
inner join personrecs pr on h.parentid = pr.id
inner join hierarchy uh on uh.parentid = pr.id and uh.pos = 0
inner join persontermgroup upt on uh.id = upt.id
)
select * from prefnames
union
select * from varnames
order by rec_url, nametype
----

== Persons with email address value(s)

[source, sql]
----
with alldata as (
	select per.id as personid, pt.termdisplayname, pt.title, pt.forename, pt.initials, pt.surname, pt.nameadditions,
	eg.email || coalesce(' (type: ' || eg.emailtype || ')', '') as email,
	ehier.pos as emailorder
from persons_common per
inner join misc on per.id = misc.id and misc.lifecyclestate != 'deleted'
inner join hierarchy phier on per.id = phier.id
inner join contacts_common con on con.initem = phier.name
inner join hierarchy ehier on con.id = ehier.parentid and ehier.primarytype = 'emailGroup'
inner join emailgroup eg on eg.id = ehier.id
inner join hierarchy pthier on per.id = pthier.parentid and pthier.primarytype = 'personTermGroup' and pthier.pos = 0
inner join persontermgroup pt on pthier.id = pt.id
),
names as (
select distinct personid, termdisplayname, title, forename, initials, surname, nameadditions
	from alldata
),
emails as (
select personid, string_agg(email, '|' order by emailorder) as email
from alldata
	group by personid
)

select termdisplayname, title, forename, initials, surname, nameadditions, email
from names
inner join emails on emails.personid = names.personid
----

== All authority terms in an instance with alternate terms and IDs

NOTE: Does not include Material authority, which is only defined/used in the `materials` domain profile.

[source,sql]
----
with authvocabs as (
select auth.vocabtype as authority,
  auth.displayname as authority_vocab,
  auth.shortIdentifier as vocabshortid,
  hier.name as vocabcsid from
(select auth.id,auth.vocabtype, auth.displayname, auth.shortIdentifier
from chronologyauthorities_common auth
union
select auth.id,auth.vocabtype, auth.displayname, auth.shortIdentifier
from citationauthorities_common auth
union
select auth.id,auth.vocabtype, auth.displayname, auth.shortIdentifier
from conceptauthorities_common auth
union
select auth.id,auth.vocabtype, auth.displayname, auth.shortIdentifier
from locationauthorities_common auth
union
select auth.id,auth.vocabtype, auth.displayname, auth.shortIdentifier
from orgauthorities_common auth
union
select auth.id,auth.vocabtype, auth.displayname, auth.shortIdentifier
from personauthorities_common auth
union
select auth.id,auth.vocabtype, auth.displayname, auth.shortIdentifier
from placeauthorities_common auth
union
select auth.id,auth.vocabtype, auth.displayname, auth.shortIdentifier
from taxonomyauthority_common auth
union
select auth.id,auth.vocabtype, auth.displayname, auth.shortIdentifier
from workauthorities_common auth
) auth
inner join hierarchy hier on auth.id = hier.id
),
altterms as (
select hier.parentid as termid,
string_agg(terms.termdisplayname, '|' order by hier.pos) as altterms from
(
select at.id, at.termdisplayname from chronologytermgroup at
union
select at.id, at.termdisplayname from citationtermgroup at
union
select at.id, at.termdisplayname from concepttermgroup at
union
select at.id, at.termdisplayname from loctermgroup at
union
select at.id, at.termdisplayname from orgtermgroup at
union
select at.id, at.termdisplayname from persontermgroup at
union
select at.id, at.termdisplayname from placetermgroup at
union
select at.id, at.termdisplayname from taxontermgroup at
union
select at.id, at.termdisplayname from worktermgroup at
) terms
inner join hierarchy hier on hier.id = terms.id
  and hier.name like '%TermGroupList'
  and hier.pos > 0
group by hier.parentid
)

select authvocabs.authority as inauthority,
  authvocabs.authority_vocab as inauthvocabulary,
  authvocabs.vocabshortid,
  deurn(t.refname) as primaryterm,
  altterms.altterms,
  cc.uri as termuri,
  t.refname as termrefname,
  termhier.name as termcsid
from(
select terms.id, terms.refname, terms.inauthority
from chronologies_common terms
union
select terms.id, terms.refname, terms.inauthority
from citations_common terms
union
select terms.id, terms.refname, terms.inauthority
from concepts_common terms
union
select terms.id, terms.refname, terms.inauthority
from locations_common terms
union
select terms.id, terms.refname, terms.inauthority
from organizations_common terms
union
select terms.id, terms.refname, terms.inauthority
from persons_common terms
union
select terms.id, terms.refname, terms.inauthority
from places_common terms
union
select terms.id, terms.refname, terms.inauthority
from taxon_common terms
union
select terms.id, terms.refname, terms.inauthority
from works_common terms
) t
inner join misc on t.id = misc.id and misc.lifecyclestate != 'deleted'
inner join authvocabs on t.inauthority = authvocabs.vocabcsid
inner join hierarchy termhier on t.id = termhier.id
inner join collectionspace_core cc on cc.id = t.id
left outer join altterms on altterms.termid = t.id
----
